### ISSUE TITLE
`testsuites` element does not validate against the xunit2 schema because of the `skipped` attribute

### ISSUE THREAD

**Issue by carlescufi** [weiwei/junitparser#100]
[The `skipped` attribute](https://github.com/weiwei/junitparser/blob/af4f06163aa949f4944dc37bd487d95c209182df/junitparser/junitparser.py#L243) in the `testsuites` schema does not validate correctly against the [xunit2 schema](https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd#L139-L143). This is also the case with the [pytest schema](https://github.com/pytest-dev/pytest/blob/main/testing/example_scripts/junit-10.xsd#L139-L143).

**Comment by weiwei** [comment]
This should have been addressed now that we support flavors.
