### ISSUE TITLE
CLI `merge` output changed between version 1.4.2 and 1.5.0

### ISSUE THREAD

**Issue by olmokramer** [weiwei/junitparser#47]
Suppose I have the following two JUnit XML files:

**a.xml**

```xml
<?xml version='1.0' encoding='utf-8'?>
<testsuite errors="0" failures="0" name="JUnit Jupiter" skipped="0" tests="2" time="0.041">
  <testcase classname="a" name="a2()" time="0.015" />
  <testcase classname="a" name="a1()" time="0.001" />
</testsuite>
```

**b.xml**

```xml
<?xml version='1.0' encoding='utf-8'?>
<testsuite errors="0" failures="0" name="JUnit Jupiter" skipped="0" tests="2" time="0.041">
  <testcase classname="b" name="b1()" time="0.015" />
  <testcase classname="b" name="b2()" time="0.001" />
</testsuite>
```

Then when I merge them with junitparser 1.5.0 cli, with the command `junitparser merge a.xml b.xml c.xml`, I get the following output:

```xml
<?xml version='1.0' encoding='utf-8'?>
<testsuites errors="0" failures="0" skipped="0" tests="0" time="0">
  <testcase classname="B" name="b1()" time="0.015" />
  <testcase classname="B" name="b2()" time="0.001" />
</testsuites>
```

Note how only the cases of `b.xml` are included, and also the `name` of the `<testsuite>` is lost.

If instead I swap the files to be merged (i.e. `junitparser merge b.xml a.xml c.xml`) then only the cases of `a.xml` are included.

But when I merge the files using Python instead of the command line, the two files do get merged as expected:

```py
>>> import junitparser
>>> a = junitparser.JUnitXml.fromfile('a.xml')
>>> b = junitparser.JUnitXml.fromfile('b.xml')
>>> c = a + b
>>> c.write('c.xml')
>>> print(open('c.xml').read())
<?xml version='1.0' encoding='utf-8'?>
<testsuite errors="0" failures="0" name="JUnit Jupiter" skipped="0" tests="4" time="0.032">
  <testcase classname="A" name="a1()" time="0.015" />
  <testcase classname="A" name="a2()" time="0.001" />
  <testcase classname="B" name="b1()" time="0.015" />
  <testcase classname="B" name="b2()" time="0.001" />
</testsuite>
```

The files also get merged correctly when I use version 1.4.2 of the command line interface.

**Comment by weiwei** [comment]
@olmokramer I fixed this issue. Also it appears that even with the older version, if you merge those two files, it will result in 2 test suites because they are not properly merged. I fixed that as well.

Please try version 1.6.0 to see if it works for you.

**Comment by olmokramer** [comment]
Hey @weiwei, thanks for the quick fix! Much appreciated!
