### ISSUE TITLE
Exclude tests from package

### ISSUE THREAD

**Issue by Ishinomori** [weiwei/junitparser#50]
As junitparser user I would like to not have `tests` module in my enviroment. Currently installation of junitparser package install also `tests` module e. g.:
```
 > la venv/lib/python3.7/site-packages/ --blocks name
 __pycache__
 easy_install.py
 future
 future-0.18.2.dist-info
 junitparser
 junitparser-1.6.1.dist-info
 libfuturize
 libpasteurize
 past
 pip
 pip-19.2.3.dist-info
 pkg_resources
 setuptools
 setuptools-41.2.0.dist-info
 tests          <-------------------------------------
```

It cause issues when I have my own `tests` directory and run unittest - this `tests` module is also discovered.

**Comment by weiwei** [comment]
Thanks for reporting and fixing the issue! The fix is now released in version 1.6.2 🎆
