### ISSUE TITLE
JUnitXML.fromString() doesn't properly handle xml file without testsuites tag

### ISSUE THREAD

**Issue by aldosuwandi** [weiwei/junitparser#53]
Looking at how `fromFile` is [implemented](https://github.com/weiwei/junitparser/blob/master/junitparser/junitparser.py#L303)

The same if-else for xml file with and without testsuites should be implemented as well for [`fromstring` method ](https://github.com/weiwei/junitparser/blob/master/junitparser/junitparser.py#L174)

Otherwise, the `fromstring` method will always produce empty test suites for a file without `testsuites` tag

**Comment by weiwei** [comment]
Thanks for reporting @aldosuwandi 

Please try 1.6.3 to see if it's fixed for you.
