### ISSUE TITLE
Failure to parse xUnit2

### ISSUE THREAD

**Issue by yoram-s** [weiwei/junitparser#54]
Hi,
The current junitparser is only compatible with xUnit v1 XML format which is deprecated in many places i.e. [xUnit.net v1 XML Format](https://xunit.net/docs/format-xml-v1)
When attempting to parse junit.xml created with v2 format, it fails i.e. [xUnit.net v2 XML Format](https://xunit.net/docs/format-xml-v2)
We are using as input the junit.xml file generated by pytest, starting from v6.0 their default is xunit2 schema

Please update your module to support the new format.

**Comment by weiwei** [comment]
Thanks for reporting @yoram-s. I'll work on it.

**Comment by weiwei** [comment]
Hi @yoram-s,

According to tests inside the pytest repo, the `xunit2` format is validated against [this schema](https://github.com/pytest-dev/pytest/blob/f54ec30a6d7969eba6a2003b4409d33828cd406d/testing/example_scripts/junit-10.xsd), which `junitparser` should already support. There are some pytest specific elements and attributes that aren't supported OOTB, but there shouldn't be errors.

Could you provide a copy of your xml file so I can look into it?

**Comment by callicles** [comment]
I think I might have just hit that issue:

https://github.com/pytest-dev/pytest/issues/5891

**Comment by weiwei** [comment]
Hi @callicles ,

I fixed it in a new (beta) version, please install and try it out:

`pip install junitparser==2.0.0b1`

Note that there is an API change: the test result is now a list of entries, instead of a single item.

**Comment by weiwei** [comment]
Close due to inactivity
