### ISSUE TITLE
Support rare Eclipse/JUnit 3 <testrun> ?

### ISSUE THREAD

**Issue by inorton** [weiwei/junitparser#59]
Hi, I'm in the process of porting [junit2html](https://gitlab.com/inorton/junit2html) over from its own internal Junit parser to your fantastic new one.   Out of the input files in my tests I have one slightly unusual report that Junitparser won't parse.

I added support for it to junit2html from a bug report https://github.com/inorton/junit2html/issues/29 which is apparently a Junit report document produced by Eclipse that encapsulates test suites inside a `<testrun>` tag.

I have a sample file here - https://gitlab.com/inorton/junit2html/-/blob/master/tests/junit-testrun.xml

Apparently it is a Junit 3 format - https://stackoverflow.com/questions/4165800/junit-test-timing-in-eclipse

**Comment by weiwei** [comment]
Looks like just a different top-level element name. I'll see what I can do.

**Comment by weiwei** [comment]
Hi @inorton 

Sorry for replying late. One way I can see is to do something like this:

```
# Create a custom TestRun element
class TestRun(Element):
    _tag = 'testrun'
    name = Attr()
    ...

# Create a custom parser to handle the file
class Junit3Xml(JunitXml):
...
    @classmethod
    def fromfile(cls, filepath, parse_func=None):
        """Initiate the object from a report file."""
        if parse_func:
            tree = parse_func(filepath)
        else:
            tree = etree.parse(filepath)  # nosec
        root_elem = tree.getroot()
        if root_elem.tag == "testsuites":
            instance = cls()
        elif root_elem.tag == "testsuite":
            instance = TestSuite()
		elif root_elem.tag == "testrun":
			instance = TestRun()
        else:
            raise JUnitXmlError("Invalid format.")
        instance._elem = root_elem
        instance.filepath = filepath
        return instance
```

I'm not sure if I need to add support for Junit 3. It seems to be quite old. I'll consider it if I see more requirements.
