### ISSUE TITLE
Parse errors with basic Jenkins results

### ISSUE THREAD

**Issue by inorton** [weiwei/junitparser#60]
I have been using your 2.0.0 beta release and have come across a problem when parsing some simple files such as this single report with one suite containing one test case.  This is a genuine report from JUnit generate some time ago.

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="JUnitXmlReporter.constructor" errors="0" skipped="1" tests="3" failures="1" time="0.006" timestamp="2013-05-24T10:23:58">
    <properties>
        <property name="java.vendor" value="Sun Microsystems Inc." />
        <property name="compiler.debug" value="on" />
        <property name="project.jdk.classpath" value="jdk.classpath.1.6" />
    </properties>
    <testcase classname="JUnitXmlReporter.constructor" name="should default path to an empty string" time="0.1">
        <failure message="test failure">Assertion failed</failure>
    </testcase>
</testsuite>
```
I would expect to be able to iterate the suite and case easily eg:
```
import junitparser
xml = junitparser.JUnitXml.fromfile("tests/junit-simple_suite.xml")
for suite in xml:
    print(suite.name)
    for test in suite:
        print(test.classname + " " + test.name)
```
However, The output I get is:
```        
should default path to an empty string
Traceback (most recent call last):
  File "<input>", line 4, in <module>
AttributeError: 'Failure' object has no attribute 'classname'
```
When I iterate the report instead of getting a `TestSuite` I seem to be getting the first `TestCase` (when it prints the suite name we get the name of the first test)

**Comment by TerrenceWongDuo** [comment]
I see this issue as well. I think the parser is expecting a <testsuites> before the list of <testsuite> which my pytest junit output does not have

**Comment by StephaneCapponi** [comment]
It seems that the issue comes from the fact that the xml given  does not contain multiple testsuite.
This would have worked if your xml would have looked like:

`<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="JUnitXmlReporter.constructor" errors="0" skipped="1" tests="3" failures="1" time="0.006" timestamp="2013-05-24T10:23:58">
        <properties>
            <property name="java.vendor" value="Sun Microsystems Inc." />
            <property name="compiler.debug" value="on" />
            <property name="project.jdk.classpath" value="jdk.classpath.1.6" />
        </properties>
        <testcase classname="JUnitXmlReporter.constructor" name="should default path to an empty string" time="0.1">
            <failure message="test failure">Assertion failed</failure>
        </testcase>
    </testsuite>
</testsuites>`

As the tag "testsuites" is not required this should still work.

**Comment by inorton** [comment]
Yes, It is an earlier form of junit xml but is still a valid one.  It's a pity that until recently there has not really been a proper schema

**Comment by StephaneCapponi** [comment]
You might be able to solve this issue by modifying the fromfile function like this:

```
@classmethod
def fromfile(cls, filepath):
"""Initiate the object from a report file."""
tree = etree.parse(filepath)
root_elem = tree.getroot()
if root_elem.tag in ('testsuites', 'testsuite'):
    instance = cls()
    if root_elem.tag == 'testsuite':
        instance.add_testsuite(TestSuite.fromelem(root_elem))
    else:
        instance._elem = root_elem
else:
    raise JUnitXmlError("Invalid format.")
instance.filepath = filepath
return instance
```

Maybe @weiwei  can have a look. I don't know is this can still be valid

**Comment by weiwei** [comment]
Hi @inorton ,

You might want to check https://github.com/weiwei/junitparser/blob/cd62b5243a57573f1641fc65dbabdbf322a05bb4/tests/test_fromfile.py#L84 about how such xml files are supposed to be handled. Basically how you iterate the XML depends on how the file is structured. If there is only one `testsuite`, iterating will get you testcases.
