### ISSUE TITLE
Conversion of suite.time changed by multiplication of 1000

### ISSUE THREAD

**Issue by marincandenza** [weiwei/junitparser#61]
Our tests show that the conversion of a test suite time has changed, see screenshot. 
I guess before version 2.0 no multiplication with 1000 was done. 

installed junitparser-2.0.0
Python3.9.0

![image](https://user-images.githubusercontent.com/45242624/104325944-73180800-54e9-11eb-8013-5027b3d87a93.png)

**Comment by marincandenza** [comment]
I'm not sure why but after building our environment again the error did not show up again.

**Comment by weiwei** [comment]
Let's wait a bit to see if it resurfaces.

**Comment by weiwei** [comment]
I suppose it got better by itself :relief:
