### ISSUE TITLE
Xml numbers parsed with system locale

### ISSUE THREAD

**Issue by EnricoMi** [weiwei/junitparser#64]
Since version 2.0.0, junitparser uses the system's locale to parse times in the XML file, where it should use the file's locale. No matter on which system you parse the same JUnit file, it should always parse the correct number.

I presume, JUnit XML files always use `en_US` or `C` locale to format float numbers like the time. At least I would expect this to be the default locale to use to parse these files.

When I parse my files with system's locale `de_DE`, I end up with wrong numbers. Running my tests with `LC_ALL=C`, parsed times match the numbers in the JUnit file.

**Comment by EnricoMi** [comment]
I would argue that setting the locale in a library is not a good idea as it sets the locale for the entire Python process, hence leaking into the application that uses the library:

https://github.com/weiwei/junitparser/blob/3f6565a85213b1f0b3da19dd4f41f0352ed4e733/junitparser/junitparser.py#L40

The `en_US` or better `C` locale should be used for the specific parse call.

**Comment by EnricoMi** [comment]
Python `locale` documentation clearly says [this is a bad idea](https://docs.python.domainunion.de/3/library/locale.html#background-details-hints-tips-and-caveats):

> It is generally a bad idea to call setlocale() in some library routine, since as a side effect it affects the entire program.
> Saving and restoring it is almost as bad: it is expensive and affects other threads that happen to run before the settings
> have been restored.

So a different approach to parse the string to float with `C` locale is required.

**Comment by weiwei** [comment]
Hi @EnricoMi, 

Thanks for pointing that out. I've merged your PR.

Cheers

**Comment by EnricoMi** [comment]
Thanks!
