### ISSUE TITLE
support disabled test cases

### ISSUE THREAD

**Issue by igagis** [weiwei/junitparser#69]
Some JUnit report producers support `disabled` test cases.
For example, JUnit report format description here: https://llg.cubic.org/docs/junit/ has `disabled` attribute on `testsuites` and `testsuite` tags. Would be nice to support that feature in `junitparser`.

This is needed in context of https://github.com/EnricoMi/publish-unit-test-result-action/issues/143

**Comment by weiwei** [comment]
Hi @igagis 

The linked schema appears to be supported by the `xunit` jenkins plugin, but not the `junit` plugin (which was what I referenced in the beginning). 

Please check https://github.com/weiwei/junitparser#handling-custom-xml-attributes to see if it fixes your issue.
