### ISSUE TITLE
Add support for "blocked" state

### ISSUE THREAD

**Issue by okainov** [weiwei/junitparser#70]
I'm not sure whether Junit has a proper spec, but nevertheless, in our team we have reports with more than just pass-fail-skip, in particular, we do have "blocked" state. It would be great if junitparser could support it.

Example:
```
		<testcase classname="mytest.type" name="test name" status="blocked"><blocked /></testcase>
```

**Comment by EnricoMi** [comment]
@okainov there is some semi-spec for Junit XML: https://llg.cubic.org/docs/junit/

It does not mention `blocked` though. So this feature request should be understood to generally to support arbitrary `status` values, which is pretty broad, I think.

**Comment by weiwei** [comment]
Hi @okainov, custom attributes is supported with https://github.com/weiwei/junitparser#handling-xml-with-custom-element. Please check to see if it fits you needs.

**Comment by weiwei** [comment]
Close for lack of response
