### ISSUE TITLE
Why does junitparser.Attr HTML escape its value on read

### ISSUE THREAD

**Issue by EnricoMi** [weiwei/junitparser#71]
The `Attr` class is used by classes that derive from `Element` to provided easy access to common attributes. For instance, `TestCase` has an `Attr` called `name`, which refers to the `name` attribute of the respective `<testcase>` element.

When I read (get) such an attribute, the string value is HTML escaped by calling into `html.escape`:

https://github.com/weiwei/junitparser/blob/c27bff20fb316496cd8ad473d5785f9a2dc62524/junitparser/junitparser.py#L85-L90

What is the rational behind escaping the string value? Given junitparser provides access to JUnit data stored in XML files, I would expect the XML / HTML aspect being stripped away, so I retrieve pure text data.

Another contradiction is that writing an attribute (set) does not do the opposite operation. You would expect setting and then getting a value to retrieve the identical value that you have set:

    from junitparser.junitparser import TestCase

    testcase = TestCase()
    testcase.name = 'abc & def'
    assert testcase.name == 'abc & def'

The assertion fails:

    abc &amp; def != abc & def

**Comment by weiwei** [comment]
It was added by @alde to address #27 -- it generates broken xmls when unescaped.

I tried without escaping and I don't see the issue. Maybe @alde can help verify if he's still around.

If it's no longer the issue, I think we can remove the escaping.

**Comment by EnricoMi** [comment]
Writing an `JUnitXml` through `JUnitXml.write` with quotes in attributes worked just fine back then. Python xml package takes care of it and writes valid XML. There is no code in #27 that reproduces the invalid XML. So it is not clear why Junitparser did not work for the user.

The PR then seems to fix the issue for the user but at the totally wrong place in the library, breaking functionality for others. And `test_quoted_attr` tests that Attr return escaped values but does not test the initial problem invalid XML itself.

The merged change is completely unjustified. The value of an `Attr` has to be the pure un-escaped string value. If that is to be written as the attribute of an XML file or XML string, the user has to escape it, but the lib has to provide the pure value.

**Comment by weiwei** [comment]
OK. I'll fix it in a new version.
