### ISSUE TITLE
Unclosed file object in setup.py

### ISSUE THREAD

**Issue by markgras** [weiwei/junitparser#73]
The `read` function in `setup.py` is implemented as such:
```
def read(fname):
    try:
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    except IOError:
        return ''
```
This function creates a file object via an `open` call, but then does not close it. One should not depend on garbage collection to clean up resources. See the [Python docs](https://docs.python.org/3/reference/datamodel.html#object.__del__) for details.

Changing the function like so fixes this issue:
```
def read(fname):
    try:
        with open(os.path.join(os.path.dirname(__file__), fname)) as f:
            return f.read()
    except IOError:
        return ''
```
Alternatively, you can switch over to using `setuptools`' [declarative config](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html), which can handle this for you.

**Comment by weiwei** [comment]
Thanks for the suggestions. I think I'll go with the simpler one.
