### ISSUE TITLE
Typo in to_concole parameters

### ISSUE THREAD

**Issue by markgras** [weiwei/junitparser#74]
In `junitparser.py`, the `JUnitXml.write` method as well as the `write_xml` function have `to_concole` parameters. I believe that this is a typo and that it is supposed to be `to_console`.

**Comment by weiwei** [comment]
Thanks for the fix!

**Comment by russlevy** [comment]
Will there be a new release for this?

**Comment by weiwei** [comment]
@russlevy Current latest version 2.4.1 has the fix.
