### ISSUE TITLE
merge is broken after typo fix

### ISSUE THREAD

**Issue by petterssonandreas** [weiwei/junitparser#78]
`junitparser merge` is broken since v2.4.0, after the typo fix in https://github.com/weiwei/junitparser/commit/ae78dd61a1389924d51d33def488cb112f3f5f47

Fixed in https://github.com/weiwei/junitparser/pull/77

**Comment by markgras** [comment]
I apologize for breaking this. The unit tests do not test the command-line interface, so the tests passed after I made my changes. Perhaps we should consider modifying/adding unit tests.

**Comment by petterssonandreas** [comment]
No worries! But yes, some tests of the CLI could be good.

**Comment by weiwei** [comment]
@petterssonandreas Thanks for the issue and PR. v2.4.1 is published to fix this.

@markgras No worries. I am also to blame for not covering it.
