### ISSUE TITLE
Writing to Element textcontent

### ISSUE THREAD

**Issue by matlerbru** [weiwei/junitparser#87]
Hi. I am trying to emulate the pytest junit xml reports using your library.
So far it is going very well. However I am not able to find any option to write to the textcontent of an element.

For example, I have a custom element called stdin, and i would like to do something like:
`<stdin>Something here</stdin>`

I would like the same for Error:
`<error message="Failed for reason">Something here</error>`

Is this possible?

**Comment by fininicus** [comment]
I am in the same position and found that it is possible to write text to the body of the `Result` class with the `.text` getter/setter.

This should achieve what you want.

e.g.
```
result = Failure(message="Failed for reason")
result.text = "Something here"
```
Will result in:
```
<testcase>
    <failure message="Failed for reason">Something here</failure>
</testcase>
```

**Comment by weiwei** [comment]
Closing as above is the recommended way to handle custom properties.
