### ISSUE TITLE
Preserve / add testsuites.name when merging with CLI tool

### ISSUE THREAD

**Issue by yusijs** [weiwei/junitparser#93]
When running `junitparser merge --glob *.xml junit-report.xml` where the files have <testsuites name=..">, the generated xml doesn't have the name-property for the testsuites tag. We're using this to group our tests, and we're having some issues with it. 

I have found a couple workarounds which could work, but they are either messy/not stable (using sed to replace in the generated file) or more tedious to maintain (writing a custom python script where we append the name)

Would love a solution that could allow me to - in the cli - just run `junitparser merge --glob *.xml junit-report.xml --suiteName "My Test Suite"` which seems like a fairly straight forward thing to add in cli.py? Another option could be --suiteAttributes or similar which takes in a comma-separated list to be more flexible:
`junitparser merge --glob *.xml junit-report.xml --suiteAttributes "name=My Test Suite,custom=Custom Value"`

I'm not super versed in python so I'm a bit concerned about messing around to much with this myself, but can always give it a stab if that would be better. :)

**Comment by yusijs** [comment]
I attempted a pr here -> https://github.com/weiwei/junitparser/pull/94

**Comment by weiwei** [comment]
@yusijs 2.8.0 release should contain your changes. Thanks for the PR!
